### ISSUE TITLE
기타 실습을 위한 간단한 서버 애플리케이션

### ISSUE THREAD

**Issue by Below0** [shinychan95/kubernetes-study#7]
Python3 FastAPI 이용해서
Deployment 등으로 직접 애플리케이션을 띄울 때 사용할만한 간단한 도커 이미지를 만들었는데
혹시 도움이 될까 해서 공유드립니다~

https://hub.docker.com/repository/docker/l4538/k8study
위 도커 허브에 올려두었습니당

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8study-deployment
  labels:
    app: k8study
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8study
  template:
    metadata:
      labels:
        app: k8study
    spec:
      containers:
      - name: k8study
        image: l4538/k8study:0.0.1
        ports:
        - containerPort: 80
```

위는 해당 이미지를 기반으로 Deployment 오브젝트를 정의한 것이고
호스트 주소로 http 호출하게 되면 "Hello World! I'm ${HOST_IP}" 형태로 응답오게 됩니다!

직접 서비스를 생성하거나 `kubectl expose k8study-deployment`를 통해 자동으로 서비스를 생성할 수 있는데
서비스는 배포된 replica(팟 들)로 로드밸런싱 해주기 때문에 자동으로 여러 IP가 번갈아 나오는 결과를 볼 수 있습니다!
